---
language: python

# Use the new container infrastructure
sudo: required

env:
  global:
    - ROLE_NAME: mariadb
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: fedora31

# Enable docker support
services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install bats curl
  # Install dependencies for Molecule test
  - python3 -m pip install molecule yamllint ansible-lint docker netaddr
  # Check ansible and molecule version
  - ansible --version
  - molecule --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  # Renames directory to make it match with role name on Ansible Galaxy
  - cd ../
  - mv ansible-role-$ROLE_NAME bertvv.$ROLE_NAME
  - cd bertvv.$ROLE_NAME

script:
  # Run molecule test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
