# roles/mariadb/tasks/install/add-repo.yml
---

- name: Add official MariaDB repository (yum)
  ansible.builtin.template:
    src: etc_yum.repos.d_mariadb.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
    mode: '0644'
  when: ansible_distribution != 'Debian'
  tags: mariadb-repo-yum


- name: Run Debian-specific tasks
  when: ansible_distribution == 'Debian'
  tags: mariadb-repo-apt
  block:

  - name: Install gpg to add repokey (apt)
    ansible.builtin.package:
      name: gpg
      state: latest

  - name: Add official MariaDB repository key (apt)
    ansible.builtin.apt_key:
      url: https://mariadb.org/mariadb_release_signing_key.asc
      state: present

  - name: Add official MariaDB repository (apt)
    ansible.builtin.template:
      src: etc_apt_sources.list.d_mariadb.list.j2
      dest: /etc/apt/sources.list.d/mariadb.list
      mode: '0644'

  - name: Update packages cache with new repo (apt)
    ansible.builtin.apt:
      update_cache: true
