# roles/mariadb/tasks/configubuntu.yml
---
- name: Install server config file
  template:
    src: etc_my.cnf.d_server.cnf.j2
    dest: "{{ mariadb_config_server }}"
  notify: restart mariadb
  tags: mariadb

- name: Install network config file
  lineinfile:
    path: /etc/mysql/my.cnf
    regexp: "^bind_address.*$"
    line: "bind_address= {{ mariadb_bind_address }}"
  notify: restart mariadb
  tags: mariadb

- name: Install custom config file
  template:
    src: etc_my.cnf.d_custom.cnf.j2
    dest: "{{ mariadb_config_custom }}"
  when: mariadb_custom_cnf|length != 0
  notify: restart mariadb
  tags: mariadb

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness }}"
    state: present
  when: mariadb_configure_swappiness|bool
  tags: mariadb

- name: Ensure service is started
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true
  tags: mariadb
