# roles/mariadb/tasks/databases.yml
---

- name: Remove the test database
  community.mysql.mysql_db:
    name: test
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: absent
  tags: mariadb-databases-cleanup

- name: Create user defined databases
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
  with_items: "{{ mariadb_databases }}"
  register: db_creation
  tags: mariadb-databases-create

# Below, the databases are initialised, but only when the database was created
# in the previous step. This ensures idempotence.
# The tasks trigger an ansible-lint warning:
#   [503] Tasks that run when changed should likely be handlers
# That's not the case here, so the linter warning is ignored.

- name: Copy database init scripts
  ansible.builtin.template:  # noqa 503
    src: "{{ item.item.init_script }}"
    dest: "/tmp/{{ item.item.init_script|basename }}"
    mode: '0600'
  with_items: "{{ db_creation.results }}"
  when: item.changed and item.item.init_script is defined
  tags: mariadb-databases-init, mariadb-databases-scripts

- name: Initialise databases
  community.mysql.mysql_db:  # noqa 503
    name: "{{ item.item.name }}"
    state: import
    target: "/tmp/{{ item.item.init_script|basename }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
  with_items: "{{ db_creation.results }}"
  when: item.changed and item.item.init_script is defined
  tags: mariadb-databases-init

- name: Delete init scripts from the server
  ansible.builtin.file:  # noqa 503
    name: "/tmp/{{ item.item.init_script|basename }}"
    state: absent
  with_items: "{{ db_creation.results }}"
  when: item.changed and item.item.init_script is defined
  tags: mariadb-databases-init, mariadb-databases-scripts-cleanup
