# roles/mariadb/tasks/install.yml
---

- name: check if firewalld is installed
  command: rpm -q firewalld
  args:
    warn: no
  register: rpm_check

- name: Permit access to MySQL port
  firewalld:
    service: mysql
    permanent: true
    state: enabled
  when: rpm_check.stdout.find('is not installed') != -1

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  when: rpm_check.stdout.find('is not installed') != -1