# roles/mariadb/tasks/install.yml
---

- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://{{ mariadb_mirror }}/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel')|regex_replace('oraclelinux', 'centos') }}{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
  tags: mariadb

- name: Create daemon group with specified gid
  group:
    name: "{{ mariadb_system_user.name }}"
    gid: "{{ mariadb_system_user.gid }}"
    system: true
    state: present

- name: Create daemon user with specified uid
  user:
    name: "{{ mariadb_system_user.name }}"
    uid: "{{ mariadb_system_user.uid }}"
    system: true
    group: "{{ mariadb_system_user.name }}"
    shell: "{{ mariadb_system_user.shell }}"
    comment: MariaDB user
    create_home: false
    skeleton: false

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
