# roles/mariadb/tasks/install.yml
---
- name: Check Python3 present
  stat:
    path: /usr/bin/python3
  register: python3ok

#- name: correct python version selected
#  alternatives:
#    name: python
#    link: /usr/bin/python
#    path: /usr/bin/python3
#  when: python3ok.stat.exists

- name: Add an Apt signing key from URL
  apt_key:
    url: "{{ mariadb_pgp_key }}"
    state: present

- name: Add official MariaDB repository
  apt_repository:
    repo: "{{ mariadb_apt_repositories }}"
    state: present
  tags: mariadb

- name: Install Install MariaDB
  apt:
    name: "{{ mariadb_packages }}"
    state: latest
    update_cache: yes
  tags: mariadb

- name: Install MySQL-python
  apt:
    name: "{% ansible_python['version']['major'] is version('3', '==') | ternary('python3-pymysql', 'python-pymysql' %}"
    state: latest

