# roles/mariadb/tasks/main.yml
---
- name: Include distribution dependent variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution_file_variety }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution_file_variety }}.yml"
  tags: mariadb

- name: Import tasks to Install MariaDB
  ansible.builtin.import_tasks: install.yml
  tags: mariadb, mariadb-install

- name: Import tasks to Configure MariaDB
  ansible.builtin.import_tasks: config.yml
  tags: mariadb, mariadb-config

- name: Import tasks to Add SSL certificates
  ansible.builtin.import_tasks: certificates.yml
  when:
    - mariadb_ssl_ca_crt != None
    - mariadb_ssl_server_crt != None
    - mariadb_ssl_server_key != None
  tags: mariadb, mariadb-config, mariadb-ssl

- name: Authentication changes in version 10.4 message
  ansible.builtin.debug:
    msg: >
      Authentication has changed in version 10.4. Both the root user and
      the user that owns the data directory (mysql by default) now utilize
      the unix_socket plugin for passwordless access, and are created with
      an invalid password. Therefore setting a password isn't required for
      those user accounts accessing via the unix socket. Please see
      https://mariadb.org/authentication-in-mariadb-10-4/ .
      Skipping authentication setup tasks!
  when: mariadb_version is version('10.4', '>=')
  tags: mariadb

- name: Import tasks to Set the database root password
  ansible.builtin.import_tasks: root-password.yml
  when:
    - not mariadb_auth_unix_plugin
    - mariadb_version is version('10.4', '<')
  tags: mariadb, mariadb-config, mariadb-rootpwd

- name: Import tasks to Enable plugin unix_socket
  ansible.builtin.import_tasks: auth-unix-plugin.yml
  when:
    - mariadb_auth_unix_plugin
    - mariadb_version is version('10.4', '<')
  tags: mariadb, mariadb-config, mariadb-authunix

- name: Import tasks to Create and initialize databases
  ansible.builtin.import_tasks: databases.yml
  tags: mariadb, mariadb-init, mariadb-databases

- name: Import tasks to Create users
  ansible.builtin.import_tasks: users.yml
  tags: mariadb, mariadb-init, mariadb-users

- name: Import tasks to Open firewall port
  when: mariadb_firewall_backend != None
  ansible.builtin.import_tasks: firewall.yml
  tags: mariadb, mariadb-firewall
