# roles/mariadb/tasks/main.yml
---
- name: Include distribution dependent variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution_file_variety }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution_file_variety }}.yml"
  tags: mariadb

- name: Install MariaDB
  ansible.builtin.include_tasks: install.yml
  tags: mariadb

- name: Configure MariaDB
  ansible.builtin.include_tasks: config.yml
  tags: mariadb

- name: Add SSL certificates
  ansible.builtin.include_tasks: certificates.yml
  when:
    - mariadb_ssl_ca_crt != None
    - mariadb_ssl_server_crt != None
    - mariadb_ssl_server_key != None
  tags: mariadb

- name: Authentication changes in version 10.4 message
  ansible.builtin.debug:
    msg: >
      Authentication has changed in version 10.4. Both the root user and
      the user that owns the data directory (mysql by default) now utilize
      the unix_socket plugin for passwordless access, and are created with
      an invalid password. Therefore setting a password isn't required for
      those user accounts accessing via the unix socket. Please see
      https://mariadb.org/authentication-in-mariadb-10-4/ .
      Skipping authentication setup tasks!
  when: mariadb_version is version('10.4', '>=')
  tags: mariadb

- name: Set the database root password
  ansible.builtin.include_tasks: root-password.yml
  when:
    - not mariadb_auth_unix_plugin
    - mariadb_version is version('10.4', '<')
  tags: mariadb

- name: Enable plugin unix_socket
  ansible.builtin.include_tasks: auth-unix-plugin.yml
  when:
    - mariadb_auth_unix_plugin
    - mariadb_version is version('10.4', '<')
  tags: mariadb

- name: Create and initialize databases
  ansible.builtin.include_tasks: databases.yml
  tags: mariadb

- name: Create users
  ansible.builtin.include_tasks: users.yml
  tags: mariadb

- name: Open firewall port
  when: mariadb_firewall_backend != None
  ansible.builtin.include_tasks: firewall.yml
  tags: mariadb
