---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint -v .

platforms:
  - name: db
    hostname: db
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tty: true
    environment:
      container: docker

provisioner:
  name: ansible

verifier:
  name: ansible
